### ISSUE TITLE
Error en asignar tutor

### ISSUE THREAD

**Issue by nitanilla** [Jeremylazm/AppSistemaTutoria#134]
![image](https://user-images.githubusercontent.com/1106435/134780336-d226d7a9-4d78-4957-8382-d2efe50be4d8.png)

**Comment by nitanilla** [comment]
en el mismo dashboard. no entra a la opcion alumnos
![image](https://user-images.githubusercontent.com/1106435/134780380-f46ab15b-2af7-485a-b443-6eaa5b42e43f.png)

**Comment by rjcastillolopez** [comment]
Se ha corregido la excepción a través de un mensaje de error. Se debe seleccionar previamente un tutor para asignar uno o más tutorados.
